### PR TITLE
Add instances for time-1.11 / time-compat-1.9.4 types: Month, Quarter, QuarterOfYear

### LINKED ISSUE #811: Support new types in time-1.11
I'll work on this ASAP (working on `time-compat` atm to backport the new types).

### PR DESCRIPTION
**Pull request by phadej**
Resolve #811

### CODE REVIEW

**Comment by phadej** [comment]
ping

**Comment by bergmark** [comment]
Will try to look through this today/tomorrow, sorry for the delay!

**Comment by phadej** [comment]
ping

**Comment by phadej** [comment]
I see https://hackage.haskell.org/package/aeson-1.5.5.0 on Hackage, thanks @bergmark !

**Pull request merged**
